name:                notebook
permalink:           pretty


# Setup
title:               notebook
tagline:             'This is my personal notebook ^_^'
description:         ''
url:                 xzenggit.github.io/cn/
baseurl:             /cn
paginate:            5

# About/contact
author:
  name:              Xiangming Zeng
  url:               ''
  email:             ''

# Custom vars√ü
version:             1.0.0
